### PR TITLE
Prepend path in the bundle install handler

### LINKED ISSUE #3: No such file or directory on first run
First run of this role:

```
RUNNING HANDLER [openmicroscopy.jekyll-build : update bundle] ****************************************************************
fatal: [infra-testpr.openmicroscopy.org]: FAILED! => {"changed": false, "cmd": "bundle install", "failed": true, "msg": "[Errn
o 2] No such file or directory", "rc": 2}

```

but a re-run, with `-v` to assist with debugging, and the role succeeded.

So there may be a sequence bug with some part of the play relying on something which has not yet been created, which _is_ created later on.

### PR DESCRIPTION
**Pull request by sbesson**
Fixes #3 - see also https://github.com/openmicroscopy/infrastructure/pull/283

In addition to Travis, this can be tested using `molecule test --driver vagrant`

### CODE REVIEW

**Comment by joshmoore** [comment]
Propose `1.1.2`?

**Comment by sbesson** [comment]
Absolutely, that's a bug fix and is worth a patch release for me

**Comment by manics** [comment]
Look fine to me (I'm undecided on whether updating `PATH` as here or using `/usr/local/bin/bundle` would be considered "best practice").

**Comment by kennethgillen** [comment]
If this method works, I'd just get it in, and we can refactor later, with no other strong opinions.

**Comment by sbesson** [comment]
Merging and tagging as 1.1.2

**Pull request merged**
